---
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.2.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.3.3
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.4.0-preview3
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  allow_failures:
    - rvm: 2.4.0-preview3
notifications:
  email: false
