name		'juniorsysadmin-irqbalance'
version		'0.0.1' 
source		'git://github.com/juniorsysadmin/puppet-irqbalance.git'
author		'Ben Spiccia'
summary		'Module for installing and configuring the irqbalance daemon'
description 	'This module installs and configures the irqbalance daemon. It ignores options not supported by the irqbalance version that comes with the distribution.'
license     	'Apache License, Version 2.0'

dependency  'puppetlabs/stdlib', '>= 3.0.0'
project_page 'https://github.com/juniorsysadmin/puppet-irqbalance'
